# Generated by Django 4.2 on 2023-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Укажите подробное описание товара', verbose_name='Описание')),
                ('structure', models.TextField(help_text='Укажите компоненты через запятую (,)', verbose_name='Состав')),
                ('price', models.IntegerField(help_text='Введите только число', verbose_name='Цена')),
                ('country_manufacture', models.CharField(help_text='Страна производства товара', max_length=50, verbose_name='Производство')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('volume', models.IntegerField(verbose_name='Объём продукта')),
                ('unit_of_measurement_of_volume', models.CharField(choices=[('kg', 'кг'), ('g', 'гр'), ('l', 'л'), ('ml', 'мл'), ('sachet', 'cаше'), ('portion', 'порции')], max_length=100, verbose_name='Выберите единицу измерения объёма продукта')),
                ('date', models.DateField(verbose_name='Дата поступления товара')),
            ],
        ),
    ]
