# Generated by Django 4.2 on 2023-04-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='uploads/', verbose_name='Фото товара'),
        ),
    ]
