# Generated by Django 4.2 on 2023-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_brand2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='country',
            field=models.CharField(max_length=128, null=True, verbose_name='Страна бренда'),
        ),
    ]
