# Generated by Django 4.2 on 2023-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productbrand_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Страна бренда'),
        ),
    ]
