# Generated by Django 4.2 on 2023-05-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_productbrand_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
