# Generated by Django 4.2 on 2023-05-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand2',
            new_name='brand',
        ),
    ]
