# Generated by Django 4.2.1 on 2023-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_product_brand_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='123', max_length=255, verbose_name='URL'),
        ),
    ]
