# Generated by Django 4.2.1 on 2023-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='-', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(default='-', max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма заказа')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='main.product')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
